CREATE DATABASE ESCOLA;

CREATE TABLE ALUNO (
    ID INT AUTO_INCREMET PRIMARY KEY,
    nome VARCHAR(24),
    email VARCHAR(24),
    matricula VARCHAR(24),
    endereco VARCHAR(55),
    telefone VARCHAR(15)
)